//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int Id { get; set; }
        public int Restaurant_ID { get; set; }
        public System.DateTime RequestedTime { get; set; }
        public Nullable<int> AssignBy { get; set; }
        public Nullable<int> AssignEmployee { get; set; }
        public string Status { get; set; }
        public System.DateTime PreservedTime { get; set; }
        public string FoodItem { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
