//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public int Request_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> DateDistributed { get; set; }
        public string Area { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
